config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("courseplanner.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

courseplanner/users/urls.py
from django.urls import path
from . import views

from courseplanner.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
    user_plan_view,
    autocomplete_course_codes,
    generate_course_plan,

)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("plan/", view=user_plan_view, name="plan"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("autocomplete_course_codes/", autocomplete_course_codes, name='autocomplete_course_codes'),
]

courseplanner/users/models.py
import random
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from ..utils.utils import get_graduation_years

class Term(models.TextChoices):
    FALL = 'Fall', _('Fall')
    SPRING = 'Spring', _('Spring')
    SUMMER = 'Summer', _('Summer')
    WINTER = 'Winter', _('Winter')

class Grade(models.TextChoices):
    A = 'A', _('A')
    A_MINUS = 'A-', _('A-')
    B_PLUS = 'B+', _('B+')
    B = 'B', _('B')
    B_MINUS = 'B-', _('B-')
    C_PLUS = 'C+', _('C+')
    C = 'C', _('C')
    C_MINUS = 'C-', _('C-')
    D_PLUS = 'D+', _('D+')
    D = 'D', _('D')
    F = 'F', _('F')
    PASS = 'P', _('Pass')
    WITHDRAW = 'W', _('Withdraw')
    CREDIT = 'CR', _('Credit')
    INCOMPLETE = 'I', _('Incomplete')
    WITHDRAWFAIL = 'WF', _('Withdraw Fail')
    WITHDRAWPASS = 'WP', _('Withdraw Pass')

# The degree requirements consist of
# 1) General Education
# 2) Quantitative Requirements
# 3) Major (Curriculum) Requirements
# 4) University Elective Requirements (meet 120 credits)
class User(AbstractUser):

    name = models.CharField(_("Name of User"), blank=True, max_length=255) # redundant field
    GRAD_YEARS = get_graduation_years()
    expected_grad_year = models.IntegerField(choices=GRAD_YEARS, null=True)
    expected_grad_term = models.CharField(choices=Term.choices, null=True, max_length=6)
    curriculums = models.ManyToManyField('Curriculum')

    file = models.FileField(upload_to='excel_files/', blank=True, null=True,
                            help_text="Upload your completed excel template. You may download a template on the home page.")

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

class UserCourse(models.Model):
    GRAD_YEARS = get_graduation_years()
    year = models.IntegerField(choices=GRAD_YEARS, null=True)
    semester = models.CharField(choices=Term.choices, null=True, max_length=6)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses')
    code = models.CharField(max_length=10, verbose_name=_('Course Code'))
    credits = models.IntegerField(verbose_name=_('Credits'))
    grade = models.CharField(max_length=2, choices=Grade.choices, verbose_name=_('Grade'), null=True)

    def __str__(self):
        return f'({self.credits}) {self.code} - {self.grade}'

class CourseTerm(models.Model):
    TERM_CHOICES = Term.choices

    name = models.CharField(max_length=20, choices=TERM_CHOICES, unique=True)

    def __str__(self):
        return self.name

# Abstract class for Course, CourseGroup, and possibly others
class Requirement(models.Model):

    def get_satisfiable_subset(self):
        if hasattr(self, 'course'):
            return self.course.get_satisfiable_subset() 
        elif hasattr(self, 'coursegroup'):
            return self.coursegroup.get_satisfiable_subset() 
        raise NotImplementedError("This class is abstract -- method needs to be implemented in the child class.")
    
    def get_credits(self):
        if hasattr(self, 'course'):
            return self.course.get_credits() 
        elif hasattr(self, 'coursegroup'):
            return self.coursegroup.get_credits() 
        raise NotImplementedError("This class is abstract -- method needs to be implemented in the child class.")

    def __str__(self):
        if hasattr(self, 'course'):
            return str(self.course)  
        elif hasattr(self, 'coursegroup'):
            return str(self.coursegroup)
        else:
            return super().__str__()
        
    # def __repr__(self) -> str:
    #     return str(self)
    
# Represents a single course
class Course(Requirement):

    code = models.CharField(max_length=10, unique=True, verbose_name=_('Course Code'))
    credits = models.PositiveSmallIntegerField()
    name = models.CharField(max_length=40)
    description = models.TextField()
    offered = models.ManyToManyField(CourseTerm)
    prerequisites = models.ManyToManyField('self', related_name="prereqs", symmetrical=False, blank=True)
    corequisites = models.ManyToManyField('self', related_name="coreqs", symmetrical=False, blank=True)

    def get_satisfiable_subset(self) -> set:
        return set([self])
    
    def get_credits(self) -> int:
        return self.credits

    def __str__(self):
        return f'{self.code}\n'

# Represents a collection of courses with a minimum credit requirement in order to be satisfied
class CourseGroup(Requirement):

    requirements = models.ManyToManyField(Requirement, related_name='requirements')
    minimum_credits = models.PositiveSmallIntegerField()

    def get_satisfiable_subset(self) -> set:
        accumulated_credits = 0
        satisfiable_subset = []
        all_reqs = list(self.requirements.all())

        # Keep selecting random requirements until credit constraint is satisfied
        while accumulated_credits < self.get_credits():
            # Error check here... "is requirement_set empty?"
            random_requirement = random.choice(all_reqs)
            all_reqs.remove(random_requirement)
            satisfiable_subset += random_requirement.get_satisfiable_subset()
            accumulated_credits += random_requirement.get_credits()

        return set(satisfiable_subset)
    
    def get_credits(self) -> int:
        return self.minimum_credits
    
    def __str__(self):
        result = f"CourseGroup ({self.minimum_credits} credits)\n"
        for requirement in self.requirements.all():
            result += f"\t{requirement}"
        return result

class Curriculum(models.Model):
    PROGRAM_TYPES = [
        ('MAJ', 'Major'),
        ('MIN', 'Minor'),
        ('CERT', 'Certificate'),
        ('TRCK', 'Interest Track'),
    ]

    name = models.CharField(max_length=40)
    requirements = models.ManyToManyField(Requirement)
    program_type = models.CharField(max_length=4, choices=PROGRAM_TYPES, default='MAJ')

    def display(self):
        result = ""
        for requirement in self.requirements.all():
            result += f"{requirement}"
        return result

    def __str__(self):
        return f'{self.name} | {self.get_program_type_display()}' 

courseplanner/users/views.py
from typing import Any
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    TemplateView,
)
from .forms import (
    CourseInputForm,
    UserUpdateForm,
    TranscriptUploadForm,
)
from .models import (
    UserCourse,
    Course,
)
from ..utils.utils import extract_course_info
from ..utils.course_util import generate_course_plan

from django.contrib import messages

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_courses = UserCourse.objects.filter(user=self.request.user)
        context['user_courses'] = user_courses
        return context

user_detail_view = UserDetailView.as_view()

class UserUpdateView(LoginRequiredMixin, TemplateView):

    template_name = "users/user_form.html"

    def post(self, request, *args, **kwargs):
        user = request.user
        update_form = UserUpdateForm(request.POST, request.FILES, instance=user)
        transcript_form = TranscriptUploadForm(request.POST, request.FILES)
        course_form = CourseInputForm(request.POST or None)
        user_courses = UserCourse.objects.filter(user=user)

        if "user_update_submit" in request.POST:
            if update_form.is_valid():
                update_form.save()
                return redirect(request.path_info)

        if "transcript_upload_submit" in request.POST:
            if transcript_form.is_valid():
                uploaded_file = transcript_form.cleaned_data['transcript']
                courses = extract_course_info(uploaded_file)
                UserCourse.objects.filter(user=user).delete()
                for course in courses:
                    UserCourse.objects.create(user=user, year=course[0], semester=course[1], code=course[2], credits=course[3], grade=course[4])
                messages.success(request, uploaded_file)

        if "course_input_submit" in request.POST:
            if course_form.is_valid():
                new_course = course_form.save(commit=False)
                new_course.user = user
                new_course.save()
                messages.success(request, "Course added successfully!")
                return redirect(request.path_info)

        if "remove_course_submit" in request.POST:
            course_id = request.POST.get("course_id")
            if course_id:
                UserCourse.objects.filter(id=course_id, user=user).delete()
                messages.success(request, "Course removed successfully!")
                return redirect(request.path_info)
            
        if "remove_all_submit" in request.POST:
            UserCourse.objects.filter(user=user).delete()
            messages.success(request, "All courses removed successfully!")
            return redirect(request.path_info)

        return self.render_to_response({'update_form': update_form, 'transcript_form': transcript_form, 'course_form': course_form, 'user_courses': user_courses})

    def get(self, request, *args, **kwargs):
        user = request.user
        update_form = UserUpdateForm(instance=request.user)
        transcript_form = TranscriptUploadForm
        course_form = CourseInputForm()
        user_courses = UserCourse.objects.filter(user=user)

        return self.render_to_response({'update_form': update_form, 'transcript_form': transcript_form, 'course_form': course_form, 'user_courses': user_courses})

    # Consider using this to reduce if branching?
    # def form_valid(self, form):
    #     if 'transcript-submit' in self.request.POST:
    #         form.save()
    #         return super().form_valid(form)
    #     else:
    #         return super().form_valid(form)

user_update_view = UserUpdateView.as_view()

# Autocomplete for UserUpdateView querying course codes.
def autocomplete_course_codes(request):
    term = request.GET.get('term')
    courses = Course.objects.filter(name__icontains=term)
    course_codes = [course.code for course in courses]
    return JsonResponse(course_codes, safe=False)
                  
class UserPlanView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/plan.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     user = self.request.user
    #     semesters, graph = generate_course_plan(user.curriculums.all(), 16)
    #     context['semesters'] = semesters
    #     context['graph'] = graph
    #     return context
    
    def post(self, request, *args, **kwargs):
        user = self.request.user
        semesters, graph = generate_course_plan(user.curriculums.all(), 16)
        return render(request, self.template_name, {'semesters': semesters, 'graph': graph})

user_plan_view = UserPlanView.as_view()

class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

courseplanner/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Edit Profile</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>

<br>
<h3>Academic History</h3>
<table class="table table-striped ">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Year</th>
      <th scope="col">Semester</th>
      <th scope="col">Course Code</th>
      <th scope="col">Credits</th>
      <th scope="col">Grade</th>
    </tr>
  </thead>
  <tbody>
    {% for course in user_courses %}
      <tr>
        <td>{{ course.year }}</td>
        <td>{{ course.semester }}</td>
        <td>{{ course.code }}</td>
        <td>{{ course.credits }}</td>
        <td>{{ course.grade }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

courseplanner/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}Edit Profile | {{ user.username }}{% endblock %}

{% block extra_js %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
{% endblock %}

{% block content %}
  <h1>Profile Setup</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- {{ update_form|crispy }} -->

    {{ update_form.file|as_crispy_field }}
    <div class="fieldWrapper">
      <label class="form-label">{% trans "Expected Graduation*" %}</label>
      <div class="form-group row">
        <div class="col-sm-5">
          {{ update_form.expected_grad_year.errors|as_crispy_errors }}
          {{ update_form.expected_grad_year }}
        </div>
        <div class="col-sm-5">
          {{ update_form.expected_grad_term.errors|as_crispy_errors }}
          {{ update_form.expected_grad_term }}
        </div>
      </div>
      {{ update_form.curriculums|as_crispy_field }}
    </div>

    <button type="submit" name="user_update_submit" class="btn btn-primary">Update Profile</button>
  </form>

  <hr>

  <h2>Add Courses</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ transcript_form|crispy }}
    <button type="submit" name="transcript_upload_submit" class="btn btn-primary">Upload Transcript</button>
  </form>

  <br>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- {{ course_form|crispy }} -->
    <div class="fieldWrapper">
        <div class="form-group row">
        <div class="col-sm">
          <div class="autocomplete-field">
            {{ course_form.code|as_crispy_field }}
          </div>
        </div>
        <div class="col-sm">
          {{ course_form.year|as_crispy_field }}
        </div>
        <div class="col-sm">
          {{ course_form.semester|as_crispy_field }}
        </div>
        <div class="col-sm">
          {{ course_form.credits|as_crispy_field }}
        </div>
        <div class="col-sm">
          {{ course_form.grade|as_crispy_field }}
        </div>
        <div class="col-sm">
          <br id="pseudo-label">
          <div>
            <button aria-label="add course" type="submit" name="course_input_submit" class="btn btn-secondary"><i class="fas fa-solid fa-plus"></i></button>
          </div>
        </div>
      </div>
    </div>
  </form>

  <br>

  <!-- Add this button inside your template -->
  <div class="d-flex justify-content-end">
    <form id="remove-all-courses-form" method="post" style="display:inline;">
      {% csrf_token %}
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#removeAllCoursesModal">
        Remove All Courses
      </button>
      <input type="hidden" name="remove_all_submit">
    </form>
  </div>

  <!-- Confirmation Modal -->
  <div class="modal fade" id="removeAllCoursesModal" tabindex="-1" role="dialog" aria-labelledby="removeAllCoursesModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="removeAllCoursesModalLabel">Warning!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete all listed courses? This action is irreversible!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger" name="remove_all_submit" onclick="document.getElementById('remove-all-courses-form').submit();">Delete</button>
        </div>
      </div>
    </div>
  </div>

  <br>

  <style>
    .remove-course-btn {
      border: none;
      background-color: transparent;
      color: red;
      cursor: pointer;
    }

    .remove-course-btn:hover {
      color: darkred;
    }
    
    #pseudo-label {
      margin-bottom: .5rem;
    }
  </style>

<table class="table table-striped ">
  <thead class="thead-dark">
    <tr>
      <th scope="col"></th>
      <th scope="col">Year</th>
      <th scope="col">Semester</th>
      <th scope="col">Course Code</th>
      <th scope="col">Credits</th>
      <th scope="col">Grade</th>
    </tr>
  </thead>
  <tbody>
    {% for course in user_courses %}
      <tr>
        <th scope="row">
          <form method="post" style="display:inline;">
            {% csrf_token %}
            <input type="hidden" name="course_id" value="{{ course.id }}">
            <button aria-label="remove course" type="submit" name="remove_course_submit" class="remove-course-btn">
              <i class="fas fa-trash-alt"></i>
            </button>
          </form>
        </th>
        <td>{{ course.year }}</td>
        <td>{{ course.semester }}</td>
        <td>{{ course.code }}</td>
        <td>{{ course.credits }}</td>
        <td>{{ course.grade }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{#% For autocompletion %#}
<script>
  $(function() {
      $("#id_name").autocomplete({
          source: "{% url 'users:autocomplete_course_codes' %}",
      });
  });
</script>


{% endblock %}